/*
 * Ski trip micro service
 * Micro service to book a ski trip
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.skitrip.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * BuySkiPassRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-27T21:00:53.025+01:00[Europe/Belgrade]")
public class BuySkiPassRequest {
  @JsonProperty("person")
  private Person person = null;

  @JsonProperty("skiPass")
  private SkiPass skiPass = null;

  public BuySkiPassRequest person(Person person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  public Person getPerson() {
    return person;
  }

  public void setPerson(Person person) {
    this.person = person;
  }

  public BuySkiPassRequest skiPass(SkiPass skiPass) {
    this.skiPass = skiPass;
    return this;
  }

   /**
   * Get skiPass
   * @return skiPass
  **/
  public SkiPass getSkiPass() {
    return skiPass;
  }

  public void setSkiPass(SkiPass skiPass) {
    this.skiPass = skiPass;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuySkiPassRequest buySkiPassRequest = (BuySkiPassRequest) o;
    return Objects.equals(this.person, buySkiPassRequest.person) &&
        Objects.equals(this.skiPass, buySkiPassRequest.skiPass);
  }

  @Override
  public int hashCode() {
    return Objects.hash(person, skiPass);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuySkiPassRequest {\n");
    
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    skiPass: ").append(toIndentedString(skiPass)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
