/*
 * Ski trip micro service
 * Micro service to book a ski trip
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.skitrip.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;
import java.util.Objects;
/**
 * SkiEquipment
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-27T21:00:53.025+01:00[Europe/Belgrade]")
public class SkiEquipment {
  @JsonProperty("equipmentType")
  private String equipmentType = null;

  @JsonProperty("rentalDuration")
  private String rentalDuration = null;

  @JsonProperty("price")
  private BigDecimal price = null;

  public SkiEquipment equipmentType(String equipmentType) {
    this.equipmentType = equipmentType;
    return this;
  }

   /**
   * Get equipmentType
   * @return equipmentType
  **/
  public String getEquipmentType() {
    return equipmentType;
  }

  public void setEquipmentType(String equipmentType) {
    this.equipmentType = equipmentType;
  }

  public SkiEquipment rentalDuration(String rentalDuration) {
    this.rentalDuration = rentalDuration;
    return this;
  }

   /**
   * Get rentalDuration
   * @return rentalDuration
  **/
  public String getRentalDuration() {
    return rentalDuration;
  }

  public void setRentalDuration(String rentalDuration) {
    this.rentalDuration = rentalDuration;
  }

  public SkiEquipment price(BigDecimal price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SkiEquipment skiEquipment = (SkiEquipment) o;
    return Objects.equals(this.equipmentType, skiEquipment.equipmentType) &&
        Objects.equals(this.rentalDuration, skiEquipment.rentalDuration) &&
        Objects.equals(this.price, skiEquipment.price);
  }

  @Override
  public int hashCode() {
    return Objects.hash(equipmentType, rentalDuration, price);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SkiEquipment {\n");
    
    sb.append("    equipmentType: ").append(toIndentedString(equipmentType)).append("\n");
    sb.append("    rentalDuration: ").append(toIndentedString(rentalDuration)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
