/*
 * Ski trip micro service
 * Micro service to book a ski trip
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.skitrip.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * SkiEquipmentRental
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-27T21:00:53.025+01:00[Europe/Belgrade]")
public class SkiEquipmentRental {
  @JsonProperty("person")
  private Person person = null;

  @JsonProperty("skiEquipment")
  private SkiEquipment skiEquipment = null;

  public SkiEquipmentRental person(Person person) {
    this.person = person;
    return this;
  }

  /**
   * Get person
   * @return person
   **/
  public Person getPerson() {
    return person;
  }

  public void setPerson(Person person) {
    this.person = person;
  }

  public SkiEquipmentRental skiEquipment(SkiEquipment skiEquipment) {
    this.skiEquipment = skiEquipment;
    return this;
  }

  /**
   * Get skiEquipment
   * @return skiEquipment
   **/
  public SkiEquipment getSkiEquipment() {
    return skiEquipment;
  }

  public void setSkiEquipment(SkiEquipment skiEquipment) {
    this.skiEquipment = skiEquipment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SkiEquipmentRental skiEquipmentRental = (SkiEquipmentRental) o;
    return Objects.equals(this.person, skiEquipmentRental.person) &&
            Objects.equals(this.skiEquipment, skiEquipmentRental.skiEquipment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(person, skiEquipment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SkiEquipmentRental {\n");

    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    skiEquipment: ").append(toIndentedString(skiEquipment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
