//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.26 at 09:36:28 PM CET 
//


package org.bp.skiequipment;

import org.bp.skiequipment.CalculateRentalCost;
import org.bp.skiequipment.CalculateRentalCostResponse;
import org.bp.skiequipment.Person;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.bp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CalculateRentalCost_QNAME = new QName("http://skiequipment.bp.org/", "calculateRentalCost");
    private final static QName _CalculateRentalCostResponse_QNAME = new QName("http://skiequipment.bp.org/", "calculateRentalCostResponse");
    private final static QName _CancelBooking_QNAME = new QName("http://skiequipment.bp.org/", "cancelBooking");
    private final static QName _CancelBookingResponse_QNAME = new QName("http://skiequipment.bp.org/", "cancelBookingResponse");
    private final static QName _RentSkiEquipment_QNAME = new QName("http://skiequipment.bp.org/", "rentSkiEquipment");
    private final static QName _RentSkiEquipmentResponse_QNAME = new QName("http://skiequipment.bp.org/", "rentSkiEquipmentResponse");
    private final static QName _Fault_QNAME = new QName("http://skiequipment.bp.org/", "Fault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CalculateRentalCost }
     * 
     */
    public CalculateRentalCost createCalculateRentalCost() {
        return new CalculateRentalCost();
    }

    /**
     * Create an instance of {@link CalculateRentalCostResponse }
     * 
     */
    public CalculateRentalCostResponse createCalculateRentalCostResponse() {
        return new CalculateRentalCostResponse();
    }

    /**
     * Create an instance of {@link CancelBooking }
     * 
     */
    public CancelBooking createCancelBooking() {
        return new CancelBooking();
    }

    /**
     * Create an instance of {@link CancelBookingResponse }
     * 
     */
    public CancelBookingResponse createCancelBookingResponse() {
        return new CancelBookingResponse();
    }

    /**
     * Create an instance of {@link RentSkiEquipment }
     * 
     */
    public RentSkiEquipment createRentSkiEquipment() {
        return new RentSkiEquipment();
    }

    /**
     * Create an instance of {@link RentSkiEquipmentResponse }
     * 
     */
    public RentSkiEquipmentResponse createRentSkiEquipmentResponse() {
        return new RentSkiEquipmentResponse();
    }

    /**
     * Create an instance of {@link Fault }
     * 
     */
    public Fault createFault() {
        return new Fault();
    }

    /**
     * Create an instance of {@link SkiEquipmentRental }
     * 
     */
    public SkiEquipmentRental createSkiEquipmentRental() {
        return new SkiEquipmentRental();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link SkiEquipment }
     * 
     */
    public SkiEquipment createSkiEquipment() {
        return new SkiEquipment();
    }

    /**
     * Create an instance of {@link BookingInfo }
     * 
     */
    public BookingInfo createBookingInfo() {
        return new BookingInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CalculateRentalCost }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CalculateRentalCost }{@code >}
     */
    @XmlElementDecl(namespace = "http://skiequipment.bp.org/", name = "calculateRentalCost")
    public JAXBElement<CalculateRentalCost> createCalculateRentalCost(CalculateRentalCost value) {
        return new JAXBElement<CalculateRentalCost>(_CalculateRentalCost_QNAME, CalculateRentalCost.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CalculateRentalCostResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CalculateRentalCostResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://skiequipment.bp.org/", name = "calculateRentalCostResponse")
    public JAXBElement<CalculateRentalCostResponse> createCalculateRentalCostResponse(CalculateRentalCostResponse value) {
        return new JAXBElement<CalculateRentalCostResponse>(_CalculateRentalCostResponse_QNAME, CalculateRentalCostResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelBooking }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CancelBooking }{@code >}
     */
    @XmlElementDecl(namespace = "http://skiequipment.bp.org/", name = "cancelBooking")
    public JAXBElement<CancelBooking> createCancelBooking(CancelBooking value) {
        return new JAXBElement<CancelBooking>(_CancelBooking_QNAME, CancelBooking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelBookingResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CancelBookingResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://skiequipment.bp.org/", name = "cancelBookingResponse")
    public JAXBElement<CancelBookingResponse> createCancelBookingResponse(CancelBookingResponse value) {
        return new JAXBElement<CancelBookingResponse>(_CancelBookingResponse_QNAME, CancelBookingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RentSkiEquipment }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RentSkiEquipment }{@code >}
     */
    @XmlElementDecl(namespace = "http://skiequipment.bp.org/", name = "rentSkiEquipment")
    public JAXBElement<RentSkiEquipment> createRentSkiEquipment(RentSkiEquipment value) {
        return new JAXBElement<RentSkiEquipment>(_RentSkiEquipment_QNAME, RentSkiEquipment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RentSkiEquipmentResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RentSkiEquipmentResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://skiequipment.bp.org/", name = "rentSkiEquipmentResponse")
    public JAXBElement<RentSkiEquipmentResponse> createRentSkiEquipmentResponse(RentSkiEquipmentResponse value) {
        return new JAXBElement<RentSkiEquipmentResponse>(_RentSkiEquipmentResponse_QNAME, RentSkiEquipmentResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fault }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Fault }{@code >}
     */
    @XmlElementDecl(namespace = "http://skiequipment.bp.org/", name = "Fault")
    public JAXBElement<Fault> createFault(Fault value) {
        return new JAXBElement<Fault>(_Fault_QNAME, Fault.class, null, value);
    }

}
